"""initial schema

Revision ID: 6743bf65fcad
Revises: 
Create Date: 2026-04-09 18:25:15.492069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6743bf65fcad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('mileage_in', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicles_vin'), ['vin'], unique=True)

    op.create_table('service_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('assigned_mechanic_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('mileage_in', sa.Integer(), nullable=True),
    sa.Column('customer_complaint', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('promised_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_mechanic_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_tickets_assigned_mechanic_id'), ['assigned_mechanic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_ticket_number'), ['ticket_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_tickets_urgency'), ['urgency'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tickets_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('service_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_notes_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_ticket_id'))

    op.drop_table('status_history')
    with op.batch_alter_table('service_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_notes_ticket_id'))

    op.drop_table('service_notes')
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_tickets_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_urgency'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_created_at'))
        batch_op.drop_index(batch_op.f('ix_service_tickets_assigned_mechanic_id'))

    op.drop_table('service_tickets')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_vin'))
        batch_op.drop_index(batch_op.f('ix_vehicles_license_plate'))
        batch_op.drop_index(batch_op.f('ix_vehicles_customer_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
